// components/AppMenu.svelte
<script lang="ts">
import { clickOutside } from "../modules/utils";

export let name: string;
let exposed: boolean = false;

function handleOpenMenu(e) {
	exposed = !exposed;
}
</script>

<div
	class="app-menu"
	use:clickOutside={() => {
		exposed = false;
		console.log("c outside");
	}}
>
	<button on:click={handleOpenMenu} class="app-menu-btn">{name}</button>
	{#if exposed}
		<div class="menu-content">
			<slot />
		</div>
	{/if}
</div>

// react/AppMenu.tsx
import type { ReactNode } from "react";

interface AppMenuProps {
	name: string;
	children?: ReactNode;
}

export default function AppMenu({ name, children }: AppMenuProps) {
	return (
		<div className="app-menu">
			<button className="app-menu-btn">{name}</button>
			<div className="menu-content">{children}</div>
		</div>
	);
}
