// solid/AppMenu.tsx
import { Dynamic } from "solid-js/web";

function AppMenuDev(props: { name: string; children?: any }) {
	return (
		<div className="app-menu">
			<button className="app-menu-btn">{props.name}</button>
			<div className="menu-content">{props.children}</div>
		</div>
	);
}

export default AppMenuDev;

// react/AppMenu.tsx
import type { ReactNode } from "react";

interface AppMenuProps {
	name: string;
	children?: ReactNode;
}

export default function AppMenu({ name, children }: AppMenuProps) {
	return (
		<div className="app-menu">
			<button className="app-menu-btn">{name}</button>
			<div className="menu-content">{children}</div>
		</div>
	);
}
