// components/AppMenuItem.svelte
<script lang="ts">
import { Menu } from "@/ts/Stores";

export let id: string;
export let name: string;
export let accelerator: string | null = null;
export let disabled: boolean = false;
export let icon: string | null = null;
export let checked: string | null = null;
</script>

<button
	class="app-menu-item"
	class:disabled
	on:click={() => {
		$Menu.handle(id);
	}}
>
	{#if checked == "true"}
		<img src="./icons/menu_win/checked.svg" alt="" />
	{:else if checked == "false"}
		<img src="" alt="" style="visibility: hidden;" />
	{:else if icon != null}
		<img src={icon} alt="" />
	{/if}
	<p class="name">{name}</p>
	{#if accelerator != null}
		<p class="accelerator">{accelerator}</p>
	{/if}
</button>

// react/AppMenuItem.tsx
import { useMenuHandler } from "@/ts/Stores";

interface AppMenuItemProps {
	id: string;
	name: string;
	accelerator?: string | null;
	disabled?: boolean;
	icon?: string | null;
	checked?: string | null;
}

export default function AppMenuItem({
	id,
	name,
	accelerator,
	disabled = false,
	icon,
	checked,
}: AppMenuItemProps) {
	const handler = useMenuHandler();

	return (
		<button
			className={`app-menu-item ${disabled ? "disabled" : ""}`}
			onClick={() => {
				handler.handle(id);
			}}
			disabled={disabled}
		>
			{checked === "true" ? (
				<img src="./icons/app_menu/checked.svg" alt="" />
			) : icon ? (
				<img src={icon} alt="" />
			) : (
				<img alt="" style={{ visibility: "hidden" }} />
			)}
			<p className="name">{name}</p>
			{accelerator ? <p className="accelerator">{accelerator}</p> : null}
		</button>
	);
}
