// components/NavItem.svelte
<script lang="ts">
interface Props {
	name: string;
	icon: string | null;
	onClick: Function;
	active: boolean;
	depth?: number;
}

let { name, icon, onClick, active, depth = 0 }: Props = $props();
</script>

<button
	class="nav-item"
	class:active
	onclick={() => {
		active = !active;
		onClick();
	}}
	class:odd={depth % 2 == 1}
>
	{#if icon}
		<img src={`./icons/topbar/${icon}.svg`} alt="" class="icon" />
	{/if}
	<p>{name}</p>
</button>

// react/NavItem.tsx
interface NavItemProps {
	name: string;
	icon: string | null;
	onClick: () => void;
	active: boolean;
	depth?: number;
}

export default function NavItem({
	name,
	icon,
	onClick,
	active,
	depth = 0,
}: NavItemProps) {
	return (
		<button
			className={`nav-item ${active ? "active" : ""} ${depth % 2 === 1 ? "odd" : ""}`}
			onClick={onClick}
		>
			{icon ? (
				<img src={`./icons/topbar/${icon}.svg`} alt="" className="icon" />
			) : null}
			<p>{name}</p>
		</button>
	);
}
