// components/TopBarDropdownItem.svelte
<script lang="ts">
export let name: string;
export let checked: boolean = false;
export let onChange;
</script>

<button
	class="item"
	on:click={() => {
		checked = !checked;
		onChange();
	}}
>
	{#if checked == true}
		<img src="./icons/menu_win/checked.svg" alt="" />
	{:else if checked == false}
		<img src="" alt="" style="visibility: hidden;" />
	{/if}
	<p class="name">{name}</p>
</button>

// react/TopBarDropdownItem.tsx
interface TopBarDropdownItemProps {
	name: string;
	checked?: boolean;
	onChange?: () => void;
	disabled?: boolean;
}

export default function TopBarDropdownItem({ name, checked, onChange = () => {}, disabled = false }: TopBarDropdownItemProps) {
	return (
		<button className={`item ${disabled ? "disabled" : ""}`} onClick={() => onChange()} disabled={disabled}>
			{checked === undefined ? (
				<img src="" alt="" style={{ visibility: "hidden" }} />
			) : checked ? (
				<img src="./icons/app_menu/checked.svg" alt="" />
			) : (
				<img src="" alt="" style={{ visibility: "hidden" }} />
			)}
			<p className="name">{name}</p>
		</button>
	);
}
