// components/AppMenuDev.svelte
<script lang="ts">
import { uiPlatform, theme, settings } from "@/ts/Stores.svelte";
import AppMenu from "./AppMenu.svelte";
import { saveSettings } from "@/ts/SaveLoad.svelte";

interface Props {
	platforms?: Array<"mac" | "win" | "web">;
	themes?: boolean;
	appName: string;
	children?: any;
}

let {
	platforms = ["mac", "win", "web"],
	themes = true,
	appName,
	children,
}: Props = $props();
</script>

<AppMenu name="Dev">
	{#if platforms.includes("mac")}
		<button
			class="app-menu-item"
			onclick={() => {
				$uiPlatform = "mac";
				saveSettings($settings, $uiPlatform, appName);
			}}
		>
			{#if $uiPlatform == "mac"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">mac</p>
		</button>
	{/if}
	{#if platforms.includes("win")}
		<button
			class="app-menu-item"
			onclick={() => {
				$uiPlatform = "win";
				saveSettings($settings, $uiPlatform, appName);
			}}
		>
			{#if $uiPlatform == "win"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">win</p>
		</button>
	{/if}
	{#if platforms.includes("web")}
		<button
			class="app-menu-item"
			onclick={() => {
				$uiPlatform = "web";
				saveSettings($settings, $uiPlatform, appName);
			}}
		>
			{#if $uiPlatform == "web"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">web</p>
		</button>
	{/if}
	{#if themes}
		<div class="seperator"></div>
		<button
			class="app-menu-item"
			onclick={() => {
				$theme = "dark";
			}}
		>
			{#if $theme == "dark"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">dark</p>
		</button>
		<button
			class="app-menu-item"
			onclick={() => {
				$theme = "light";
			}}
		>
			{#if $theme == "light"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">light</p>
		</button>
	{/if}

	{@render children?.()}
</AppMenu>

// solid/AppMenuDev.tsx
import { Show } from "solid-js";
import AppMenu from "./AppMenu";
import { setUiPlatform, uiPlatform } from "../../ts/Stores";

function AppMenuDev(props: {
	platforms?: Array<"mac" | "win" | "web">;
	themes?: boolean;
	children?: any;
}) {
	return (
		<AppMenu name="Dev">
			<Show when={props.platforms?.includes("mac")}>
				<button
					className="app-menu-item"
					onClick={() => {
						setUiPlatform("mac");
					}}
				>
					<Show when={uiPlatform() === "mac"}>
						<img src="./icons/app_menu/checked.svg" alt="" />
					</Show>
					<p className="name">mac</p>
				</button>
			</Show>
			<Show when={props.platforms?.includes("win")}>
				<button
					className="app-menu-item"
					onClick={() => {
						setUiPlatform("win");
					}}
				>
					<Show when={uiPlatform() === "win"}>
						<img src="./icons/app_menu/checked.svg" alt="" />
					</Show>
					<p className="name">win</p>
				</button>
			</Show>
			<Show when={props.platforms?.includes("web")}>
				<button
					className="app-menu-item"
					onClick={() => {
						setUiPlatform("web");
					}}
				>
					<Show when={uiPlatform() === "web"}>
						<img src="./icons/app_menu/checked.svg" alt="" />
					</Show>
					<p className="name">web</p>
				</button>
			</Show>
		</AppMenu>
	);
}

export default AppMenuDev;
