// react/AppMenuDev.tsx
import useStore from "@/ts/Stores";
import AppMenu from "./AppMenu";
import { saveSettings } from "@/ts/SaveLoad";

interface AppMenuDevProps {
	platforms?: Array<"mac" | "win" | "web" | "liquidGlass">;
	themes?: boolean;
	appName: string;
}

export default function AppMenuDev({
	platforms = ["mac", "win", "web", "liquidGlass"],
	themes = true,
	appName,
}: AppMenuDevProps) {
	const uiPlatformValue = useStore(s => s.uiPlatform);
	const themeValue = useStore(s => s.theme);
	const settingsValue = useStore(s => s.settings);
	const setUiPlatform = useStore(s => s.setUiPlatform);
	const setStoreTheme = useStore(s => s.setTheme);

	function setPlatform(value: "mac" | "win" | "web" | "liquidGlass") {
		setUiPlatform(value);
		saveSettings(settingsValue, value, appName);
	}

	function setTheme(value: "dark" | "light") {
		setStoreTheme(value);
	}

	return (
		<AppMenu name="Dev">
			{platforms.includes("mac") && (
				<button className="app-menu-item" onClick={() => setPlatform("mac")}>
					{uiPlatformValue === "mac" && (
						<img src="./icons/app_menu/checked.svg" alt="" />
					)}
					<p className="name">mac</p>
				</button>
			)}
			{platforms.includes("liquidGlass") && (
				<button
					className="app-menu-item"
					onClick={() => setPlatform("liquidGlass")}
				>
					{uiPlatformValue === "liquidGlass" && (
						<img src="./icons/app_menu/checked.svg" alt="" />
					)}
					<p className="name">liquidGlass</p>
				</button>
			)}
			{platforms.includes("win") && (
				<button className="app-menu-item" onClick={() => setPlatform("win")}>
					{uiPlatformValue === "win" && (
						<img src="./icons/app_menu/checked.svg" alt="" />
					)}
					<p className="name">win</p>
				</button>
			)}
			{platforms.includes("web") && (
				<button className="app-menu-item" onClick={() => setPlatform("web")}>
					{uiPlatformValue === "web" && (
						<img src="./icons/app_menu/checked.svg" alt="" />
					)}
					<p className="name">web</p>
				</button>
			)}
			{themes && (
				<>
					<div className="seperator" />
					<button className="app-menu-item" onClick={() => setTheme("dark")}>
						{themeValue === "dark" && (
							<img src="./icons/app_menu/checked.svg" alt="" />
						)}
						<p className="name">dark</p>
					</button>
					<button className="app-menu-item" onClick={() => setTheme("light")}>
						{themeValue === "light" && (
							<img src="./icons/app_menu/checked.svg" alt="" />
						)}
						<p className="name">light</p>
					</button>
				</>
			)}
		</AppMenu>
	);
}

// components/AppMenuDev.svelte
<script lang="ts">
	import { uiPlatform, theme, settings } from "@/ts/Stores.svelte";
	import AppMenu from "./AppMenu.svelte";
	import { saveSettings } from "@/ts/SaveLoad.svelte";

	interface Props {
		platforms?: Array<"mac" | "win" | "web" | "liquidGlass">;
		themes?: boolean;
		appName: string;
		children?: any;
	}

	let {
		platforms = ["mac", "win", "web", "liquidGlass"],
		themes = true,
		appName,
		children,
	}: Props = $props();
</script>

<AppMenu name="Dev">
	{#if platforms.includes("mac")}
		<button
			class="app-menu-item"
			onclick={() => {
				$uiPlatform = "mac";
				saveSettings($settings, $uiPlatform, appName);
			}}
		>
			{#if $uiPlatform == "mac"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">mac</p>
		</button>
	{/if}
	{#if platforms.includes("liquidGlass")}
		<button
			class="app-menu-item"
			onclick={() => {
				$uiPlatform = "liquidGlass";
				saveSettings($settings, $uiPlatform, appName);
			}}
		>
			{#if $uiPlatform == "liquidGlass"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">liquidGlass</p>
		</button>
	{/if}
	{#if platforms.includes("win")}
		<button
			class="app-menu-item"
			onclick={() => {
				$uiPlatform = "win";
				saveSettings($settings, $uiPlatform, appName);
			}}
		>
			{#if $uiPlatform == "win"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">win</p>
		</button>
	{/if}
	{#if platforms.includes("web")}
		<button
			class="app-menu-item"
			onclick={() => {
				$uiPlatform = "web";
				saveSettings($settings, $uiPlatform, appName);
			}}
		>
			{#if $uiPlatform == "web"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">web</p>
		</button>
	{/if}
	{#if themes}
		<div class="seperator"></div>
		<button
			class="app-menu-item"
			onclick={() => {
				$theme = "dark";
			}}
		>
			{#if $theme == "dark"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">dark</p>
		</button>
		<button
			class="app-menu-item"
			onclick={() => {
				$theme = "light";
			}}
		>
			{#if $theme == "light"}
				<img src="./icons/app_menu/checked.svg" alt="" />
			{/if}
			<p class="name">light</p>
		</button>
	{/if}

	{@render children?.()}
</AppMenu>
