// react/NavFolder.tsx
import { ReactNode, useEffect, useState } from "react";

interface NavFolderProps {
	name: string;
	icon: string | null;
	onClick?: () => void;
	active: boolean;
	exposed: boolean;
	depth?: number;
	children?: ReactNode;
}

export default function NavFolder({ name, icon, onClick = () => {}, active, exposed, depth = 0, children }: NavFolderProps) {
	const [isExposed, setIsExposed] = useState(exposed);

	useEffect(() => {
		setIsExposed(exposed);
	}, [exposed]);

	return (
		<div className={`nav-folder ${isExposed ? "exposed" : ""} ${depth % 2 === 1 ? "odd" : ""}`}>
			<div className={`nav-item ${active ? "active" : ""}`} onClick={() => onClick()}>
				<button
					className="expander"
					onClick={e => {
						e.stopPropagation();
						setIsExposed(prev => !prev);
					}}
				>
					<img src="./icons/std/dropdown_arrow.svg" alt="" />
				</button>
				{icon ? <img src={`./icons/topbar/${icon}.svg`} alt="" className="icon" /> : null}
				<p>{name}</p>
			</div>
			{isExposed ? <div className="content">{children}</div> : null}
		</div>
	);
}

// components/NavFolder.svelte
<script lang="ts">
export let name: string;
export let icon: string | null = null;
export let onClick: Function = () => {};
export let active: boolean;
export let exposed: boolean = false;
</script>

<div class="nav-folder" class:exposed>
	<button class="nav-item" class:active on:click={() => {
        active = !active;
        onClick();
    }}>
		<button
			class="expander"
			on:click={e => {
                e.stopPropagation();
				exposed = !exposed;
			}}
		>
			<img src="./icons/std/dropdown_arrow.svg" alt="" />
		</button>
		{#if icon}
			<img src={`./icons/tool_bar/${icon}.svg`} alt="" class="icon" />
		{/if}
		<p>{name}</p>
	</button>

	{#if exposed}
		<div class="content">
			<slot />
		</div>
	{/if}
</div>
