// react/SelectionBox.tsx
import { useEffect, useState } from "react";

interface SelectionBoxProps {
	options: Array<{ name: string; value: any }>;
	selected: any;
	onChange?: (value: any) => void;
}

export default function SelectionBox({
	options,
	selected,
	onChange = () => {},
}: SelectionBoxProps) {
	const [selectedObj, setSelectedObj] = useState(options[0]);
	const [exposed, setExposed] = useState(false);

	useEffect(() => {
		const found = options.find(option => option.value === selected);
		if (found) {
			setSelectedObj(found);
		}
	}, [options, selected]);

	return (
		<div className="select">
			<button
				className="select-btn"
				onClick={() => {
					setExposed(prev => !prev);
					onChange(selectedObj.value);
				}}
			>
				<div className="options">
					{options.map((e, i) => (
						<p key={i} className={selectedObj === e ? "sel" : ""}>
							{e.name}
						</p>
					))}
				</div>
				<img src="./icons/std/select_arrow.svg" alt="" />
			</button>
			<div className={`option-container ${exposed ? "exposed" : ""}`}>
				{options.map((option, index) => (
					<button
						key={index}
						className={selectedObj === option ? "selected" : ""}
						onClick={() => {
							setSelectedObj(option);
							setExposed(false);
							onChange(option.value);
						}}
					>
						{option.name}
					</button>
				))}
			</div>
		</div>
	);
}

// components/SelectionBox.svelte
<script lang="ts">
	import { uiPlatform } from "@/ts/Stores";

	type option = { name: string; value: any };

	export let options: Array<option>;
	export let onChange = () => {};
	export let selected: any;
	let selectedObj: option | undefined;
	let selectedName: string = "";
	selectionChange(selected);

	let exposed = false;

	function selectionChange(sel: any) {
		if (selected) {
			selectedObj = options.find(x => x.value == selected);
			console.log(selectedObj);
			selectedName = selectedObj.name;
		}
		console.log("change selected");
	}
	$: selectionChange(selected);

	function selectionObjChange(sel: any) {
		if (selectedObj) {
			selected = selectedObj.value;
			selectedName = selectedObj.name;
		}
	}
	$: selectionObjChange(selectedObj);
</script>

{#if $uiPlatform == "mac"}
	<!--default html selection box used on macOS-->
	<select bind:value={selected}>
		{#each options as option}
			<option value={option.value}>{option.name}</option>
		{/each}
	</select>
{:else}
	<!--custom selection box used on windows and web-->
	<div class="select">
		<button
			class="select-btn"
			on:click={() => {
				exposed = true;
			}}>{selectedName}</button
		>
		<div class="option-container" class:exposed>
			{#each options as option}
				<button
					class:selected={selected == option}
					on:click={() => {
						selectedObj = option;
					}}
				>
					{option.name}
				</button>
			{/each}
		</div>
	</div>
{/if}
