// react/WinButtonsMS.tsx
interface WinButtonsMSProps {
	onMin?: () => void;
	onMax?: () => void;
	onClose?: () => void;
	CanMaximise?: boolean;
	CanMinimize?: boolean;
	CanClose?: boolean;
	CloseOnly?: boolean;
}

export default function WinButtonsMS({
	onMin = () => {},
	onMax = () => {},
	onClose = () => {},
	CanMaximise = true,
	CanMinimize = true,
	CanClose = true,
	CloseOnly = false,
}: WinButtonsMSProps) {
	return (
		<div className="win-buttons-ms" data-tauri-drag-region>
			{!CloseOnly && (
				<button onClick={onMin} className={CanMinimize ? "" : "disabled"} disabled={!CanMinimize}>
					<img src="./icons/native/winButtonsMSMin.svg" alt="" draggable="false" />
				</button>
			)}
			{!CloseOnly && (
				<button onClick={onMax} className={CanMaximise ? "" : "disabled"} disabled={!CanMaximise}>
					<img src="./icons/native/winButtonsMSMax.svg" alt="" draggable="false" />
				</button>
			)}
			<button onClick={onClose} className={`close ${!CanClose ? "disabled" : ""}`} disabled={!CanClose}>
				<img src="./icons/native/winButtonsMSClose.svg" alt="" draggable="false" />
			</button>
		</div>
	);
}

// components/WinButtonsMS.svelte
<script lang="ts">
	export let onMin = () => {}
	export let onMax = () => {}
	export let onClose = () => {}
	export let CanMaximise = true;
	export let CanMinimize = true;
	export let CanClose = true;
	export let CloseOnly = false;
</script>

<div class="win-buttons-ms" data-tauri-drag-region>
	{#if !CloseOnly}
		<button
			on:click={onMin}
			class:disabled={CanMinimize == false}
		>
			<img src="./icons/winButtonsMSMin.svg" alt="" draggable="false">
		</button>
		<button
			on:click={onMax}
			class:disabled={CanMinimize == false}
		>
			<img src="./icons/winButtonsMSMax.svg" alt="" draggable="false">
		</button>
	{/if}
	<button
		on:click={onClose}
		class="close"
		class:disabled={CanClose == false}
	>
		<img src="./icons/winButtonsMSClose.svg" alt="" draggable="false">
	</button>
</div>
