// components/settings/SettingsWebContainer.svelte
<script lang="ts">
import SettingsContent from "@/lib/SettingsContent.svelte";
import "@/pureUI/scss/_settingsWebContainer.scss";
import { settings } from "@/ts/Stores";

function onChange() {}
</script>

<dialog class="settings">
	<div class="topbar web-settings" data-tauri-drag-region>
		<p class="window-title" data-tauri-drag-region>Settings</p>
		<div class="win-buttons-web">
			<button
				on:click={() => {
					document.querySelector("dialog")?.close();
				}}
			>
				<img src="/icons/native/winButtonsWebClose.svg" alt="" />
			</button>
		</div>
	</div>

	<SettingsContent {settings} {onChange} version={"0.1"} />
</dialog>

// react/settings/SettingsWebContainer.tsx
import SettingsContent from "@/lib/SettingsContent";
import "@/pureUI/scss/_settingsWebContainer.scss";

export default function SettingsWebContainer() {
	function onChange() {
		return;
	}

	return (
		<dialog className="settings">
			<div className="topbar web-settings" data-tauri-drag-region>
				<p className="window-title" data-tauri-drag-region>
					Settings
				</p>
				<div className="win-buttons-web">
					<button
						onClick={() => {
							(
								document.querySelector("dialog") as HTMLDialogElement | null
							)?.close();
						}}
					>
						<img src="/icons/native/winButtonsWebClose.svg" alt="" />
					</button>
				</div>
			</div>

			<SettingsContent onChange={onChange} version="0.1" />
		</dialog>
	);
}
