// components/settings/SettingsCheckbox.svelte
<script lang="ts">

export let name: string;
export let checked: boolean;
export let checkboxName: string;
export let onChange = () => {};

</script>

<div class="option">
	<p class="name">{name}</p>
	<input type="checkbox" bind:checked on:change={onChange} />
	<p class="checkbox-name">{checkboxName}</p>
</div>

// react/settings/SettingsCheckbox.tsx
interface SettingsCheckboxProps {
	name: string;
	checked: boolean;
	checkboxName: string;
	onChange: () => void;
}

export default function SettingsCheckbox({
	name,
	checked,
	checkboxName,
	onChange,
}: SettingsCheckboxProps) {
	return (
		<div className="option">
			<p className="name">{name}</p>
			<input type="checkbox" checked={checked} onChange={onChange} />
			<p className="checkbox-name" onClick={onChange}>
				{checkboxName}
			</p>
		</div>
	);
}
